[project]
name = "check-cvs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pdfreader>=0.1.15",
    "pypdf2<3.0.0",
    "python-docx>=1.2.0",
    "typer>=0.16.0",
]
